### ISSUE TITLE
Change Next_? default values

### ISSUE THREAD

**Issue by kamenov** [PhilterPaper/PDF-Table#11]
Currently next_h and next_y params are getting their default values from the respective start_? params.
This behaviour should change and they should be set to 'page top' - 'margin top' so that they can use the full space of a new page.

**Comment by PhilterPaper** [comment]
Update for release 1.000: neither `next_h` nor `next_y` _have_ to be defined, but there will be a warning message if a continuation (spill) page is needed and they are not both defined. In that case, they will default to 80% and 90% of the media (page) height respectively, if not defined.
