### ISSUE TITLE
drawing a horizontal line

### ISSUE THREAD

**Issue by davewood** [PhilterPaper/PDF-Table#55]
hi, i want to have one horizontal line between 2 rows.

is there some way to do this? i cannot set the border for a single row.

**Comment by PhilterPaper** [comment]
A quick look at the documentation doesn't show a way to set a `horizontal_border` just for a single row, or on a cell-by-cell basis. I will have to consider a row_props or a cell_props to set cell borders (rules).

**Comment by davewood** [comment]
thanks for the response, I am currently adding a cell with dashes and cellspan to make a line that goes from start to end of the row. but it doesnt look so good. looking forward for such an enhancement. :)

**Comment by PhilterPaper** [comment]
In release 1.000, you can easily do this by defining a "bottom rule" for a given row, using the new "row_props" row properties list. If you want a line (thick border) between rows _N_ and _N+1_, you would define a horizontal rule for row _N_.

**Comment by davewood** [comment]
https://metacpan.org/pod/PDF::Table#border_c-Border-color-for-all-borders.

```If a setting is specified in more than one place, the order of precedence is as follows: a header property (header row only), followed by a cell property, followed by a column property, followed by a row property, followed by a global setting, and finally, any hard-coded default value (if required).```

my table doesnt habe any rules/borders and I want do draw a bottom rule after the first row (=header)

however nothing happends if I do the following:
```
    return $table->table(
        $pdf, $page, $data,
        new_page_func => $obj->{new_page_func},
        x => $x, start_y => $y, w => $w, start_h => $h,
        # optional
        font    => $obj->{font_arial},
        font_size => 10,
        next_y  => 680,
        next_h  => 620,
        padding => 2,
        header_props => { 
                          repeat => 1,
                          bg_color => '#FFFFFF',
                          font => $obj->{font_arial_bold},,
                          font_size => 10,
                          font_color => '#000000',
                        },
        border => 1,
        row_props => [{h_rule_w => 1}],
    );
```

**Comment by davewood** [comment]
it does work the other way around though. if the global $border = 1 and i set row_props =>[{h_rule_w=>1}] everything has a border except between first and second row.

**Comment by PhilterPaper** [comment]
'border' now refers only to the outside frame around the table, while 'rule' is interior dividers. The 'rules' inherit width and color from the 'border' if no 'rule' is specified. That much should be unchanged. If you want no borders or rules, and only a divider between the header row and the first data row, a 'h_rule_w' = 1 for the 0th row _or_ the 'header_props' (have you tried that?) should do the job. I'll have to look at it today and see if I can replicate it.

**Comment by davewood** [comment]
```
    return $table->table(
        $pdf, $page, $data,
        x => $x, start_y => $y, w => $w, start_h => $h,
        header_props => {
                          repeat => 1,
                          bg_color => '#FFFFFF',
                          font => $obj->{font_arial_bold},
                          font_size => 10,
                          font_color => '#000000',
                          h_rule_w => 1,
                        },
        border => 0,
    );
```

neither approach works for me.

**Comment by davewood** [comment]
here is a demo code that creates a pdf that has nor borders and no rules whatsoever.

```
#!/usr/bin/env perl

use 5.022;
use strict;
use warnings;
use PDF::API2;
use PDF::Table;

my $table = PDF::Table->new,
my $pdf   = PDF::API2->new;
my $page = $pdf->page();
my $data = [
    ['foo1','bar1','baz1'],
    ['foo2','bar2','baz2']
];
my %options = (
    'x' => 10,
    'w' => 570,
    'y' => 220,
    'h' => 180,
    border => 0,
    row_props => [{ h_rule_w => 2 },{}],
);

my ($final_page, $number_of_pages, $final_y) = $table->table( $pdf, $page, $data, %options );
$pdf->saveas('foo.pdf');
```

**Comment by PhilterPaper** [comment]
OK, I've replicated it. I'll have to look at it today to see what's going on.

**Comment by PhilterPaper** [comment]
Appears to be fixed. It was an edge case when no borders, where the graphics object was not created in some cases, so rules weren't drawn. I'll put out release 1.001 tonight.

**Comment by davewood** [comment]
works now PhilterPaper++
