### ISSUE TITLE
table without header formatting

### ISSUE THREAD

**Issue by davewood** [PhilterPaper/PDF-Table#56]
my table doesnt have a header row and I dont want a header formatting.
how can in I make the first row look the same as all the other rows?

**Comment by PhilterPaper** [comment]
Please show the code you're using that is forcing header formatting. The default should be to use normal formatting, unless you're inadvertently specifying a header. What version of PDF::Table are you running? 0.12 was just released a month ago.

**Comment by davewood** [comment]
I was using 0.11 and you are right, there was a *header_props* that I accidentally copy&pasted.
thank you for your work :) and for being helpful.
