### ISSUE TITLE
custom row_height for just one row

### ISSUE THREAD

**Issue by davewood** [PhilterPaper/PDF-Table#58]
i want to set the row_height for some rows in a table.

i tried my luck with this code
`cell_props =>[[{row_height=>10},{row_height=>10}]]`

but nothing changed.

is there a way to achieve what i need?

**Comment by PhilterPaper** [comment]
I don't see anything in the code where `cell_props` can override the global and highest-cell heights. I'll add that to the list of things to do.

**Comment by PhilterPaper** [comment]
Update for release 1.000: `row_height` (requested minimum height of a row) will be honored for one row if appearing in `row_prop` collection. An entry in `cell_prop` will also do the job.

**Comment by davewood** [comment]
thats awesome, and idea when 1.000 will be released?

**Comment by PhilterPaper** [comment]
I'm finishing it up right now. It might be out within a few days if all goes well.

**Comment by davewood** [comment]
will this also work for padding?

**Comment by PhilterPaper** [comment]
Yes. In fact, most of the settings (such as row_height and padding) will be applicable by cell (highest priority), column, row, or globally (lowest priority). I think you'll like it!
