### ISSUE TITLE
h_rule_w for last row_props is ignored

### ISSUE THREAD

**Issue by davewood** [PhilterPaper/PDF-Table#64]
I want to make a horizontal rule for the last row.

`row_props => [{},{},{},...,{h_rule_w => 1}];`

works for every row but the last one.

**Comment by PhilterPaper** [comment]
The very last row should not have a rule, but the bottom (horizontal) _border_ instead. A row's _horizontal rule_ is **below** the row itself (on the bottom of each cell). If you want a rule _above_ the last row, you would have to define the rule in the next-to-last row. If this does not resolve this issue, please attach a small sample showing the problem. Does the documentation (POD) need clarification on where rules are drawn?

It sounds like you are looking to separate the last row as a table _footer_. Is this correct? A footer (similar to a header) is on my to-do list -- if there's a demand for it, I could move up its priority.

**Comment by davewood** [comment]
I want to draw a horizontal line at the bottom of the last row of a table.

I just scanned the POD for "border" but i still dont know how that could be accomplished.

I added `h_border_w => 1` to the last row in $row_props but nothing changes


```
    $page = $obj->{table_options}{new_page_func}->();

    my $data = [
        [1,1,1],
        [2,2,2],
        [3,3,3],
    ];  

    my $row_props = [{},{},{h_border_w=>1}];
                        
    return $table->table(
        $pdf, $page, $data,
        x => $x, y => $y, w => $w, h => $h,
        border_w => 0,
        row_props => $row_props,
    );
```

doesnt draw a horizontal line at the bottom of the last row.

**Comment by PhilterPaper** [comment]
A _border_ is a global property, not something in row properties. Change `border_w =>0` to `border_w => 0, h_border_w => 1` and you should see horizontal borders at top and bottom. Unfortunately, there is no way at present to get just the bottom border, which seems to be what you want. Let me think about whether I could offer bot_h_border_w, etc., or else a way to specify a _rule_ at the very top and bottom if h_border_w is 0.

If you've got two separate tables that are "running into each other" and you need a way to visually separate them, what else have you tried? A blank line between one table and the next? A background color to distinguish the tables as unities? Drawing a rule (graphics line) between the tables? Consider `h_border_w => 1` unless you just can't have both the top and bottom borders on the tables.

**Comment by davewood** [comment]
thank you for the insight.

it doesnt make alot of sense to me that I can add a bottom rule for every row except for the last one.

ideally every table, row, cell, column should have a property to add a border for each side. top, bottom, left, right. but i understand that there are alot of constraints and that PDF is complex stuff.

the line at the bottom is something a customer is requesting from me.

**Comment by PhilterPaper** [comment]
It wouldn't be terribly hard to enable the bottom row's rule, _if the bottom (horizontal) **border** is 0 width_. That is, if there is a border, the last row's rule should not be seen. If there _is_ a bottom border, it takes precedence over a rule. Currently, though, the last row's rule is suppressed _regardless_ of whether there's a bottom border, That could be changed, but there would still be NO rule above the top row (there's no way to define one, nor a rule to the right of the right column).

It might be overall more consistent and cleaner to allow a top (or bottom) _border_ (width and color) to override the horizontal border, and likewise for left and right. This would be in the same manner as "horizontal" and "vertical" borders override the generic borders settings. The alternative would be to find a way that's not too clumsy to  define a top-row "above" rule (or right-column "right" rule), to be seen only if there is no border there. What do you think?

     border_w   (same applies to border_c)
         applies to all four sides, unless overridden
              h_border_w   override for top and bottom
                   top_border_w  (new)   override for top
                   bot_border_w  (new)   override for bottom
              v_border_w
                   left_border_w   (new)   override for left
                   right_border_w   (new)  override for right

Frankly, there are better ways to visually separate two tables (make a gap between them, with or without a rule drawn separately), but this clumsy way could be done if you absolutely insist on making it part of PDF::Table.

**Comment by davewood** [comment]
I think my misunderstanding stems from thinking of borders like the are dealt with in HTML/CSS. Your explanation makes sense though.

I will leave it up to you to add the functionality to draw the bottom border only. I would never dare to insist on a change in YOUR module.

> It might be overall more consistent and cleaner to allow a top (or bottom) border (width and color) to override the horizontal border, and likewise for left and right. This would be in the same manner as "horizontal" and "vertical" borders override the generic borders settings.

I think thats the most sane solution for my issue.

as always, thanks for your work and help.

**Comment by PhilterPaper** [comment]
If you're just looking to draw a rule to separate two tables, have you tried the code snippet I gave at the bottom of my last post? That would avoid cluttering up PDF::Table with unnecessary changes. Don't forget to (re)set line color, dash pattern, and width if necessary; and call `stroke` some time afterwards to actually draw the line. Is that not feasible for you? You could actually get a bit fancy with it for eye-pleasing effects, such as making it a bit thicker than other rules, and centered a bit shorter than the full table width. You could even use graphics to draw some eye candy such as a very short filled diamond (using `polygon`) instead of a simple line.

**Comment by davewood** [comment]
yeah I tried but it doesnt really fit into the way I manage my code. your snippet draws the line after the current table is drawn when the next table is created. sometimes i only want the bottom border at a table even if no next table follows.

```
$pdftable->table(...); # draw table Nr1
$start_y = start of next table
$start_y -= $gutter_width;
$grfx->move($left_edge, $start_y + $gutter_width/2);
$grfx->hline($left_edge + $table_width);
$pdftable->table(...); # draw table Nr2 AND the line.
```

**Comment by PhilterPaper** [comment]
Drawing a rule _is not part of Table_. That code goes in your PDF-creation program that _calls_ PDF::Table.

Anyway, give the following replacement Table.pm a try: [Table.pm.txt](https://github.com/PhilterPaper/PDF-Table/files/5827058/Table.pm.txt) (obviously you have to rename it to Table.pm and move it to the right place).

You can give (in the global area, just like `border_w`) `t_border_w`, `r_border_w`, `b_border_w`, or `l_border_w` for top, right, bottom, or left border widths. They override any `border_w`, `h_border_w`, or `v_border_w`. Let me know if it does the job for you.

**Comment by davewood** [comment]
this works but it prints the borderon every page. I only need the bottom border at the last page.

**Comment by PhilterPaper** [comment]
I think it's drawing a _rule_ in some cases when only a _b\_border\_w_ was requested (rule_w and border_w 0). Let me think about this. As I feared it would, it's getting messy.

**Comment by PhilterPaper** [comment]
I have been unable to get top and bottom border overrides to stop interfering with top- and bottom-of-page pseudo-rules (solid line marking boundary between rows, or dashed line marking a break in the middle of a row). Unless something else occurs to me, I will have to close this ticket. Please try _again_ to use graphics to draw a line dividing your table from neighboring tables or text. I already showed how to do it -- it's very easy, and a lot easier than trying to patch up PDF::Table to behave as you want, without breaking compatibility with how everyone else is used to it working.

**Comment by davewood** [comment]
alright, thanks for the help.

here is my piece of working code in case someone else needs it

```
sub draw_line {
    my ($page, $x, $y, $length) = @_;
    my $gfx = $page->gfx();
    $gfx->move($x, $y);
    $gfx->hline($x+$length);
    $gfx->stroke();
}
```

```
my @ret = $table->table(...);
# draw line at end of table
+  my $gfx_page = $ret[0];
+  my $gfx_y       = $ret[2];
+  draw_line($gfx_page, $x, $gfx_y, $w);
```
