### ISSUE TITLE
calculate table height in advance

### ISSUE THREAD

**Issue by davewood** [PhilterPaper/PDF-Table#69]
is it possible to calculate the height of the table BEFORE adding it to the pdf by executing `$pdftable->table(...)`?

example: I have 2 tables. if both of them do not fit on the current page i want to create a new page and add the two tables there.

**Comment by PhilterPaper** [comment]
In #52, I propose to add a flag to return the height of each row and the overall height, to allow you to decide the _height_ parameter desired (controlling where to split the table on each page, via an array of heights and y positions). Does that sound like something that would satisfy your request?

**Comment by PhilterPaper** [comment]
Its primary purpose is to try to fit a table across multiple pages without splitting _within_ any row, by knowing the height of each row (and the header and [future] footer). The first element (total height) is all you're interested in.

**Comment by davewood** [comment]
sounds great, any idea when this enhancement canbe expected?

as usual, thank you for the swift and productive feedback.

**Comment by PhilterPaper** [comment]
What's currently on my plate for PDF::Table:
1. fix column width problem
2. possibly implement format control (preserve source spaces)
3. row heights (the one we're discussing here)

I would _guess_ at this point to see the row heights by late summer, unless some higher priority problem (bug) shows up, in PDF::Table or PDF::Builder. Or, revenue-generating work ramps up. All I can say at this point is that it's on the list, and I will get to it as soon as I can.

**Comment by PhilterPaper** [comment]
A related item could be using something like Text::Layout formatting to determine the height of a cell, and feeding that in to PDF::Table to specify the row(s) height. That is, externally specify the height of row(s) via `min_rh` but using that as an absolute height and not a minimum (i.e., don't recalculate the actual vertical space needed; possibly just cut off the cell content if it overflows). In general, a `max_rh` might be useful to add (min = max = externally calculated height). The same might be done for cell _width_, too. Consideration should be given to integrating Text::Layout (or similar) into PDF::Builder to hide this extra step from the user.

**Comment by PhilterPaper** [comment]
This is in the 1.004 release just sent to CPAN. See examples/vsizes.pl for an example of using.

**Comment by davewood** [comment]
thank you so much!

I will test it and tell you about my experience!
