### ISSUE TITLE
Extract Constants

### ISSUE THREAD

**Issue by kamenov** [PhilterPaper/PDF-Table#7]
There are many hardcoded values and magic number. There have to be a PDF::Table::Constants which can export on demand all these values.

**Comment by PhilterPaper** [comment]
Can anyone give some examples of where it would be useful to have various constants available? Would these be Read Only or would they be writable?

**Comment by PhilterPaper** [comment]
Question from me:

> Are these CSS-like settings for formatting, in which case they should be writable? How about state values, such as the current Y position (updatable if desired)? Is that what you wanted?

Comment from Desislav:

> Yes, this is more having a reasonable defaults. It also relates to #5

**Comment by PhilterPaper** [comment]
Update for release 1.000: many constants and "magic numbers" are now defined in a section at the top of Table.pm. I haven't decided yet whether it's worthwhile to pull them out into a separate file.

**Comment by PhilterPaper** [comment]
As this ticket has been substantially satisfied, I will close it. I will add to the "to-do" list any methods to retrieve state data (e.g., x and y position?) that would be useful, as well as whether it's worth pulling out the constants into a separate file (the list isn't _all_ that long).
