### ISSUE TITLE
Disabling the header

### ISSUE THREAD

**Issue by abeverley** [PhilterPaper/PDF-Table#70]
I would like to render some tables without a header. Looking at the code, it is possible to do this by passing a false value to ```header_props```. I've tried this and it works as desired. However, the documentation states that ```If the 'header_props' parameter is used, it should be a hashref```

I'm wondering whether the documentation can simply be updated to include disabling the header as a recognised option? I'm happy to create a PR for this, I just wanted to check whether that's okay in principle.

**Comment by PhilterPaper** [comment]
You can always just _omit_ the `header_props` parameter to not create a header. If for some reason you _need_ to have a header_props parameter (hash element given to table()), setting it to `false` should work. What the code does is check if a header_props entry is given, _and_ it's a hashref. If not, it's ignored. "`false`" would _not_ be a hashref.

I'm not sure why a new option (or do you mean a defined specific value for `header_props`?) would be needed. I could just document that _false_ or some other thing that is not a hashref would work to suppress a header, if the `header_props` parameter needs to be given for some reason. Would that suffice?

**Comment by abeverley** [comment]
Ah, my mistake, I am using ```PDF::Table``` via ```CtrlO::PDF``` and didn't realise the latter was adding a default header_props.

> I could just document that _false_ or some other thing that is not a hashref would work to suppress a header, if the `header_props` parameter needs to be given for some reason. Would that suffice?

Nonetheless, I think that would be useful, as I don't think there is anything in the documentation to state that a header row is optional nor that it can be set to false. I spent a while reading the docs thinking that a header was mandatory. I'm happy to draft something if that would help.

Many thanks for the quick reply.

**Comment by PhilterPaper** [comment]
I've updated the documentation (POD) to clarify the matter. It won't be on GitHub for a while, until I finish up some other work.

**Comment by abeverley** [comment]
Great, thanks @PhilterPaper
