### ISSUE TITLE
Module Abstract is unknown

### ISSUE THREAD

**Issue by perlpunk** [PhilterPaper/PDF-Table#76]
The `abstract` in `META.json` and `META.yml` is `unknown`, and in `Makefile.PL` there is
```
ABSTRACT_FROM     => 'lib/PDF/Table.pm',
```
but the POD moved to `lib/PDF/Table/Table.pod`.
So no abstract is found, `perl Makefile.PL` issues a warning.

So the `ABSTRACT_FROM` should change
```
ABSTRACT_FROM     => 'lib/PDF/Table/Table.pod',
```
but I also think the pod file should move to `lib/PDF/Table.pod`, because otherwise `perldoc` might not find the pod.

I stumbled upon this while maintaining the openSUSE [perl modules repository](https://build.opensuse.org/project/show/devel:languages:perl:autoupdate)

**Comment by PhilterPaper** [comment]
OK, thanks for catching this. I have moved Table.pod and have updated Makefile.PL et al.

**Comment by perlpunk** [comment]
thanks!
